### ISSUE TITLE
Review the tests

### ISSUE THREAD

**Issue by synw** [synw/django-spaninja#4]
The branch https://github.com/synw/django-spaninja/tree/moretests has tests for the account app but they are not working correctly. I would need some help to review the code to see if I used the right tooling and eventually fix the tests that are giving wrong results

**Comment by boot-sandre** [comment]
The branch Basic unittest proposal don't cover at all "account" django-ninja app.

**Comment by boot-sandre** [comment]
#7 Will give only account state endpoints unittest

**Comment by boot-sandre** [comment]
#7 I've updated it with pretty all account endpoints/methods

**Comment by boot-sandre** [comment]
#7 merged ^
